.TH "PIXELDECK" "1" "October 2019" "" ""
.SH "NAME"
\fBpixeldeck\fR - serve games via http & html
.SH "SYNOPSIS"
.P
\fBusage:\fR \fIpixeldeck\fR \fB\[lB]-o=val, --option="{key:value}"\[rB]\fR
.P
TODO: SYNOPSIS Launching this command via
.P
.RS 2
.nf
$> pixeldeck
.fi
.RE
.P
on the command line prompt will start an http server listening for browser connections. It should print out info about how to connect, like \fI\(lahttp://localhost:4444\(ra\fR or something.
.SH "OPTIONS"
.P
TODO: OPTIONS
