const events = require('events')
const evt = module.exports = new events.EventEmitter()
const dbg = require('../dbg').extend('evt')
const arch = require('../arch')
arch.defineRequires(__dirname,evt,'Start','Restart','Stop')
evt.on('Loaded',()=>dbg('Loaded'))
evt.on('Started',()=>dbg('Start'))
evt.on('Starting',()=>dbg('Starting'))
evt.on('Restarting',()=>dbg('Restarting'))
evt.on('Restarted',()=>dbg('Restart'))
evt.on('Stopping',()=>dbg('Stopping'))
evt.on('Stopped',()=>dbg('Stop'))
dbg('loaded')